//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DPGI_vladik
{
    using System;
    using System.Collections.Generic;
    
    public partial class Numbers
    {
        public long Decimal { get; set; }
        public string Binary { get; set; }
        public string Octal { get; set; }
        public string Hexidecimal { get; set; }
    }
}
